import os.path
import pandas as pd

class RosterMissingError(Exception):

	def __init__(self, file="freshman_roster.xlsx", message='Missing "freshman_roster.xlsx"\nContact owner for roster file'):
		self.file = file
		self.message = message
		super().__init__(self.message)

site_url_list = [
"https://www.smore.com/6eyp8-stevenson-daily-digest?ref=email",
"https://www.smore.com/9s0mq-stevenson-daily-digest?ref=email",
"https://www.smore.com/591w4-stevenson-daily-digest?ref=email",
"https://www.smore.com/9f24p-stevenson-daily-digest?ref=email",
"https://www.smore.com/zbqk6-stevenson-daily-digest?ref=email",
"https://www.smore.com/28u5b-stevenson-daily-digest?ref=email",
"https://www.smore.com/mnkbs-stevenson-daily-digest?ref=email",
"https://www.smore.com/bmhwg-stevenson-daily-digest?ref=email",
"https://www.smore.com/4m5q0-stevenson-daily-digest?ref=email",
"https://www.smore.com/8zx2k-stevenson-daily-digest?ref=email",
"https://www.smore.com/qzmn8-stevenson-daily-digest?ref=email",
"https://www.smore.com/ryqap-stevenson-daily-digest?ref=email",
"https://www.smore.com/9av3g-stevenson-daily-digest?ref=email",
"https://www.smore.com/9thns-stevenson-daily-digest?ref=email",
"https://www.smore.com/7fj9d-stevenson-daily-digest?ref=email",
"https://www.smore.com/v5mhe-stevenson-daily-digest?ref=email",
"https://www.smore.com/sz5ty-stevenson-daily-digest?ref=email",
"https://www.smore.com/ny1cr-stevenson-daily-digest?ref=email",
"https://www.smore.com/ynmsq-stevenson-daily-digest?ref=email",
"https://www.smore.com/56qks-stevenson-daily-digest?ref=email",
"https://www.smore.com/7ka8u-stevenson-daily-digest?ref=email",
"https://www.smore.com/atf96-stevenson-daily-digest?ref=email",
"https://www.smore.com/tw3ng-stevenson-daily-digest?ref=email",
"https://www.smore.com/6sw81-stevenson-daily-digest?ref=email",
"https://www.smore.com/d71uk-stevenson-daily-digest?ref=email",
"https://www.smore.com/qs3r8-stevenson-daily-digest?ref=email",
"https://www.smore.com/n1vth-stevenson-daily-digest?ref=email",
"https://www.smore.com/r219p-stevenson-daily-digest?ref=email",
"https://www.smore.com/rpbfh-stevenson-daily-digest?ref=email",
"https://www.smore.com/r8tw3-stevenson-daily-digest?ref=email",
"https://www.smore.com/qgb1z-stevenson-daily-digest?ref=email",
"https://www.smore.com/ruwm1-stevenson-daily-digest?ref=email",
"https://www.smore.com/610ay-stevenson-daily-digest?ref=email",
"https://www.smore.com/zbjq5-stevenson-daily-digest?ref=email",
"https://www.smore.com/p6bmy-stevenson-daily-digest?ref=email",
"https://www.smore.com/bej48-stevenson-daily-digest?ref=email",
"https://www.smore.com/zymfv-stevenson-daily-digest?ref=email",
"https://www.smore.com/hnc09-stevenson-daily-digest?ref=email",
"https://www.smore.com/hmzru-stevenson-daily-digest?ref=email",
"https://www.smore.com/adtsmx-stevenson-daily-digest?ref=email",
"https://www.smore.com/keyzfg-stevenson-daily-digest?ref=email",
"https://www.smore.com/47nct6-stevenson-daily-digest?ref=email",
"https://www.smore.com/yjts6-stevenson-daily-digest?ref=email",
"https://www.smore.com/rpmkn-stevenson-daily-digest?ref=email",
"https://www.smore.com/0rsk8-stevenson-daily-digest?ref=email",
"https://www.smore.com/jydf1-stevenson-daily-digest?ref=email",
"https://www.smore.com/crbt4-stevenson-daily-digest?ref=email",
"https://www.smore.com/wuakz-stevenson-daily-digest?ref=email",
"https://www.smore.com/sf3x8-stevenson-daily-digest?ref=email",
"https://www.smore.com/z62b7-stevenson-daily-digest?ref=email",
"https://www.smore.com/tfe25-stevenson-daily-digest?ref=email",
"https://www.smore.com/hytfw-stevenson-daily-digest?ref=email",
"https://www.smore.com/51fws-stevenson-daily-digest?ref=email",
"https://www.smore.com/7qn3e9-stevenson-daily-digest?ref=email",
"https://www.smore.com/wx7uh-stevenson-daily-digest?ref=email",
"https://www.smore.com/evcx7-stevenson-daily-digest?ref=email",
"https://www.smore.com/1xg4f-stevenson-daily-digest?ref=email",
"https://www.smore.com/z2er1-stevenson-daily-digest?ref=email",
"https://www.smore.com/pbkny-stevenson-daily-digest?ref=email",
"https://www.smore.com/4g8u6-stevenson-daily-digest?ref=email",
"https://www.smore.com/g2bhd-stevenson-daily-digest?ref=email",
"https://www.smore.com/4sj2u-stevenson-daily-digest?ref=email",
"https://www.smore.com/7zjs8-stevenson-daily-digest?ref=email",
"https://www.smore.com/jzw9h-stevenson-daily-digest?ref=email",
"https://www.smore.com/pse0r-stevenson-daily-digest?ref=email",
"https://www.smore.com/18nky-stevenson-daily-digest?ref=email",
"https://www.smore.com/tqu4e-stevenson-daily-digest?ref=email",
"https://www.smore.com/216jh-stevenson-daily-digest?ref=email",
"https://www.smore.com/dt9ju-stevenson-daily-digest?ref=email",
"https://www.smore.com/feqpv-stevenson-daily-digest?ref=email",
"https://www.smore.com/urgyk-stevenson-daily-digest?ref=email",
"https://www.smore.com/6gh14-stevenson-daily-digest?ref=email",
"https://www.smore.com/f1gh9-stevenson-daily-digest?ref=email",
"https://www.smore.com/tw7hd-stevenson-daily-digest?ref=email",
"https://www.smore.com/djs3u-stevenson-daily-digest?ref=email",
"https://www.smore.com/es4aj-stevenson-daily-digest?ref=email",
"https://www.smore.com/epnc3-stevenson-daily-digest?ref=email",
"https://www.smore.com/qjh2v-stevenson-daily-digest?ref=email",
"https://www.smore.com/4v0u5-stevenson-daily-digest?ref=email",
"https://www.smore.com/13k8f-stevenson-daily-digest?ref=email",
"https://www.smore.com/1u90s-stevenson-daily-digest?ref=email",
"https://www.smore.com/wb3aq-stevenson-daily-digest?ref=email",
"https://www.smore.com/13av8-stevenson-daily-digest?ref=email",
"https://www.smore.com/e0ng4-stevenson-daily-digest?ref=email",
"https://www.smore.com/zaq7k-stevenson-daily-digest?ref=email",
"https://www.smore.com/ec5vj-stevenson-daily-digest?ref=email",
"https://www.smore.com/vny87-stevenson-daily-digest?ref=email",
"https://www.smore.com/9vnzr-stevenson-daily-digest?ref=email",
"https://www.smore.com/9gmx5-stevenson-daily-digest?ref=email",
"https://www.smore.com/3vwta-stevenson-daily-digest?ref=email",
"https://www.smore.com/ex31y-stevenson-daily-digest?ref=email",
"https://www.smore.com/wqvnf-stevenson-daily-digest?ref=email",
"https://www.smore.com/y21fq-stevenson-daily-digest?ref=email",
"https://www.smore.com/8fs7e-stevenson-daily-digest?ref=email",
"https://www.smore.com/fe01q8-stevenson-daily-digest?ref=email",
"https://www.smore.com/7esbg-stevenson-daily-digest?ref=email",
"https://www.smore.com/d4a70-stevenson-daily-digest?ref=email",
"https://www.smore.com/z5k23-stevenson-daily-digest?ref=email",
"https://www.smore.com/yqa6z-stevenson-daily-digest?ref=email",
"https://www.smore.com/jy2xd-stevenson-daily-digest?ref=email",
"https://www.smore.com/b35t6-stevenson-daily-digest?ref=email",
"https://www.smore.com/2dy7u-stevenson-daily-digest?ref=email",
"https://www.smore.com/m3d2s-stevenson-daily-digest?ref=email",
"https://www.smore.com/dn0sr-stevenson-daily-digest?ref=email",
"https://www.smore.com/pxmw2-stevenson-daily-digest?ref=email",
"https://www.smore.com/pagb0-stevenson-daily-digest?ref=email",
"https://www.smore.com/n6xbv-stevenson-daily-digest?ref=email",
"https://www.smore.com/eqpbu-stevenson-daily-digest?ref=email",
"https://www.smore.com/9beph-stevenson-daily-digest?ref=email",
"https://www.smore.com/n8q04-stevenson-daily-digest?ref=email",
"https://www.smore.com/mx1vs-stevenson-daily-digest?ref=email",
"https://www.smore.com/qawfg-stevenson-daily-digest?ref=email",
"https://www.smore.com/wj031-stevenson-daily-digest?ref=email",
"https://www.smore.com/ykxv6-stevenson-daily-digest?ref=email",
"https://www.smore.com/3f2q0-stevenson-daily-digest?ref=email",
"https://www.smore.com/s9g8w-stevenson-daily-digest?ref=email",
"https://www.smore.com/hb96t-stevenson-daily-digest?ref=email",
"https://www.smore.com/pa2qf-stevenson-daily-digest?ref=email",
"https://www.smore.com/8cxwb-stevenson-daily-digest?ref=email",
"https://www.smore.com/7k6va-stevenson-daily-digest?ref=email",
"https://www.smore.com/wnht1-stevenson-daily-digest?ref=email",
"https://www.smore.com/tj4ax-stevenson-daily-digest?ref=email",
"https://www.smore.com/jh1xv-stevenson-daily-digest?ref=email",
"https://www.smore.com/1we02-stevenson-daily-digest?ref=email",
"https://www.smore.com/d2axz-stevenson-daily-digest?ref=email",
"https://www.smore.com/98bm3p-stevenson-daily-digest?ref=email",
]

if os.path.exists('freshman_roster.xlsx'):
	df = pd.read_excel('freshman_roster.xlsx') 
	freshman_roster = df['Full Name'].to_list()
else:
	raise RosterMissingError()


